name: 'Continuous Integration'
on:
  push:
    branches-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  unit-tests:
    uses: ./.github/workflows/_unit_tests.yml
  integration-tests:
    uses: ./.github/workflows/_integration_tests.yml
  npm-publish:
    needs: [unit-tests, integration-tests]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: 16.x
    - name: Run semantic-release
      env:
        GH_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        curl "https://raw.githubusercontent.com/pelias/ci-tools/master/semantic-release.sh" | bash -
  build-docker-images:
    # run this job if the unit tests passed and the npm-publish job was a success or was skipped
    # note: github actions won't run a job if you don't call one of the status check functions, so `always()` is called since it evalutes to `true`
    if: ${{ always() && needs.unit-tests.result == 'success' && (needs.npm-publish.result == 'success' || needs.npm-publish.result == 'skipped') }}
    needs: [unit-tests, integration-tests, npm-publish]
    runs-on: ${{ vars.UBUNTU_VERSION }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/sea-maps/pelias-schema
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
